CREATE USER :username WITH  
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  PASSWORD ':passwd';  
GRANT USAGE ON SCHEMA public TO :username;
GRANT USAGE ON SCHEMA archiv TO :username;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO :username;
GRANT SELECT ON ALL TABLES IN SCHEMA archiv TO :username;
